export const GOOGLE_ADS_ID = "AW-XXXXXXXXX";        // preencher depois
export const CONVERSAO_WHATSAPP = "AW-XXXXXXXXX/XXXXXXXXXXXXXXXXX";
export const CONVERSAO_TELEFONE = "AW-XXXXXXXXX/XXXXXXXXXXXXXXXXX";
export const CONVERSAO_FORMULARIO = "AW-XXXXXXXXX/XXXXXXXXXXXXXXXXX";
export const MEDICAO_ATIVA = false;
